service: chatbuddy-staging-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  stage: staging
  region: eu-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment: ${file(env.json)}
