service: chatbuddy-staging-api
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  stage: staging
  region: eu-west-2

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /{proxy+}
      - http: ANY /
    environment:
      APP_NAME: ${file(env.jso./n):APP_NAME}
      NODE_ENV: ${file(./env.json):NODE_ENV}
      PORT: ${file(./env.json):PORT}
      DATABASE_LOCAL: ${file(./env.json):DATABASE_LOCAL}
      DATABASE_USERNAME: ${file(./env.json):DATABASE_USERNAME}
      DATABASE_PASSWORD: ${file(./env.json):DATABASE_PASSWORD}
      JWT_SECRET: ${file(./env.json):JWT_SECRET}
      JWT_EXPIRES_IN: ${file(./env.json):JWT_EXPIRES_IN}
      JWT_COOKIE_EXPIRES_IN: ${file(./env.json):JWT_COOKIE_EXPIRES_IN}
      MAIL_SERVICE: ${file(./env.json):MAIL_SERVICE}
      MAIL_HOST: ${file(./env.json):MAIL_HOST}
      MAIL_PORT: ${file(./env.json):MAIL_PORT}
      MAIL_USERNAME: ${file(./env.json):MAIL_USERNAME}
      MAIL_PASSWORD: ${file(./env.json):MAIL_PASSWORD}
      MAIL_FROM_ADDRESS: ${file(./env.json):MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${file(./env.json):MAIL_FROM_NAME}
      OPENAI_BASE_URL: ${file(./env.json):OPENAI_BASE_URL}
      OPENAI_API_KEY: ${file(./env.json):OPENAI_API_KEY}
      OPENAI_ORG_ID: ${file(./env.json):OPENAI_ORG_ID}
      OPENAI_GPT_MODEL: ${file(./env.json):OPENAI_GPT_MODEL}
      OPENAI_MODEL_TEMPERATURE: ${file(./env.json):OPENAI_MODEL_TEMPERATURE}
      PAYSTACK_PUBLIC_KEY: ${file(./env.json):PAYSTACK_PUBLIC_KEY}
      PAYSTACK_SECRET_KEY: ${file(./env.json):PAYSTACK_SECRET_KEY}
      PAYSTACK_BASE_URL: ${file(./env.json):PAYSTACK_BASE_URL}
      TZ: ${file(./env.json):TZ}
